// Generated by nitro
import type { Serialize, Simplify } from 'nitropack';
declare module 'nitropack' {
    type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
    interface InternalApi {
        '/__nuxt_error': {
            default: Simplify<
                Serialize<
                    Awaited<
                        ReturnType<
                            typeof import('../../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.3.3_@types+node@18.15.11_eslint@8.38.0_sass@1.61.0_terser@5.18._f2kkay35yo6qllyxbqtqvbw5um/node_modules/nuxt/dist/core/runtime/nitro/renderer').default
                        >
                    >
                >
            >;
        };
    }
}
export {};
