// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../components.plugin").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.3.3_@types+node@18.15.11_eslint@8.38.0_sass@1.61.0_terser@5.18._f2kkay35yo6qllyxbqtqvbw5um/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.3.3_@types+node@18.15.11_eslint@8.38.0_sass@1.61.0_terser@5.18._f2kkay35yo6qllyxbqtqvbw5um/node_modules/nuxt/dist/head/runtime/plugins/vueuse-head-polyfill").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.3.3_@types+node@18.15.11_eslint@8.38.0_sass@1.61.0_terser@5.18._f2kkay35yo6qllyxbqtqvbw5um/node_modules/nuxt/dist/app/plugins/router").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.3.3_@types+node@18.15.11_eslint@8.38.0_sass@1.61.0_terser@5.18._f2kkay35yo6qllyxbqtqvbw5um/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}
// TODO: remove when webstorm has support for augumenting 'vue' directly
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
